<?xml version="1.0" encoding="utf-8"?>
<robot name="exo_march6" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <material name="red">
    <color rgba="1 0 0 1"/>
  </material>
  <material name="dark_gray">
    <color rgba="0.25 0.25 0.25 1"/>
  </material>

  <!-- ============================================================
       Global / convenience
       ============================================================ -->
  <xacro:property name="PI" value="3.141592653589793"/>

  <!-- Dimensions -->
  <xacro:property name="width" value="0.05"/>
  <xacro:property name="torso_width" value="0.5"/>

  <xacro:property name="hip_base_height" value="0.145"/>
  <xacro:property name="hip_aa_frame_height" value="0.1605"/>
  <xacro:property name="hip_aa_frame_width" value="0.151"/>

  <xacro:property name="upper_leg_height" value="0.410"/>
  <xacro:property name="upper_leg_offset" value="0.00"/>

  <xacro:property name="lower_leg_height" value="0.390"/>
  <xacro:property name="knee_offset" value="0.00"/>

  <xacro:property name="ankle_plate_length" value="0.115"/>
  <xacro:property name="ankle_plate_height" value="${ankle_plate_length - width}"/>
  <xacro:property name="ankle_plate_offset" value="0.00"/>

  <xacro:property name="foot_height_forward" value="0.184"/>
  <xacro:property name="foot_height_backward" value="0.059"/>
  <xacro:property name="foot_length" value="${foot_height_forward + foot_height_backward}"/>

  <!-- Masses -->
  <xacro:property name="mass_hip_base" value="8.686"/>
  <xacro:property name="mass_hip_aa" value="3.019"/>
  <xacro:property name="mass_upper_leg" value="8.161"/>
  <xacro:property name="mass_lower_leg" value="4.997"/>
  <xacro:property name="mass_foot" value="0.789"/>

  <xacro:property name="heel_pad_length" value="0.06"/>
  <xacro:property name="heel_pad_width"  value="${width}"/>
  <xacro:property name="heel_pad_thick"  value="0.004"/>
  <xacro:property name="sole_thick" value="0.004"/>

  <!-- Inertias -->
  <xacro:property name="I_hip_base_xx" value="0.303498"/>
  <xacro:property name="I_hip_base_xy" value="-0.000197304"/>
  <xacro:property name="I_hip_base_xz" value="0.0189663"/>
  <xacro:property name="I_hip_base_yy" value="0.239254"/>
  <xacro:property name="I_hip_base_yz" value="0.00122058"/>
  <xacro:property name="I_hip_base_zz" value="0.11822"/>

  <xacro:property name="I_hip_aa_xx" value="0.068391"/>
  <xacro:property name="I_hip_aa_xy" value="-0.0426776"/>
  <xacro:property name="I_hip_aa_xz" value="0.000171569"/>
  <xacro:property name="I_hip_aa_yy" value="0.0388633"/>
  <xacro:property name="I_hip_aa_yz" value="0.00117041"/>
  <xacro:property name="I_hip_aa_zz" value="0.104156"/>

  <xacro:property name="I_upper_leg_xx" value="1.68779"/>
  <xacro:property name="I_upper_leg_xy" value="-0.0439623"/>
  <xacro:property name="I_upper_leg_xz" value="0.249519"/>
  <xacro:property name="I_upper_leg_yy" value="1.68452"/>
  <xacro:property name="I_upper_leg_yz" value="0.0814673"/>
  <xacro:property name="I_upper_leg_zz" value="0.20142"/>

  <xacro:property name="I_lower_leg_xx" value="0.567226"/>
  <xacro:property name="I_lower_leg_xy" value="0.00351928"/>
  <xacro:property name="I_lower_leg_xz" value="0.0146315"/>
  <xacro:property name="I_lower_leg_yy" value="0.561191"/>
  <xacro:property name="I_lower_leg_yz" value="-0.019722"/>
  <xacro:property name="I_lower_leg_zz" value="0.0624652"/>

  <xacro:property name="I_foot_xx" value="0.00388523"/>
  <xacro:property name="I_foot_xy" value="-0.00209516"/>
  <xacro:property name="I_foot_xz" value="-0.00189858"/>
  <xacro:property name="I_foot_yy" value="0.00659119"/>
  <xacro:property name="I_foot_yz" value="-0.00168033"/>
  <xacro:property name="I_foot_zz" value="0.00630322"/>

  <!-- Joint limits -->
  <xacro:property name="hip_min" value="${-30.0 * PI/180.0}"/>
  <xacro:property name="hip_max" value="${105.0 * PI/180.0}"/>
  <xacro:property name="knee_min" value="${0.0}"/>
  <xacro:property name="knee_max" value="${105.0 * PI/180.0}"/>
  <xacro:property name="ankle_min" value="${-45.0 * PI/180.0}"/>
  <xacro:property name="ankle_max" value="${45.0 * PI/180.0}"/>

  <xacro:property name="haa_min" value="${-20.0 * PI/180.0}"/>
  <xacro:property name="haa_max" value="${ 20.0 * PI/180.0}"/>

  <!-- ============================================================
       Base / world sliders
       ============================================================ -->
  <link name="world"/>

  <link name="base_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1.0"/>
      <inertia ixx="0.1041667" ixy="0" ixz="0"
               iyy="0.0885417" iyz="0"
               izz="0.0260417"/>
    </inertial>
    <visual>
      <origin xyz="0 0 1.3" rpy="0 0 0"/>
      <geometry><box size="0.25 0.5 1"/></geometry>
      <material name="red"/>
    </visual>
    <collision>
      <origin xyz="0 0 1.3" rpy="0 0 0"/>
      <geometry><box size="0.25 0.5 1"/></geometry>
    </collision>
  </link>

  <link name="slider_z">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia ixx="0.0002083" ixy="0" ixz="0"
               iyy="0.0002083" iyz="0"
               izz="0.0002083"/>
    </inertial>
    <collision><geometry><sphere radius="0.01"/></geometry></collision>
    <visual><geometry><sphere radius="0.01"/></geometry></visual>
  </link>

  <link name="slider_x">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia ixx="0.0002083" ixy="0" ixz="0"
               iyy="0.0002083" iyz="0"
               izz="0.0002083"/>
    </inertial>
    <collision><geometry><sphere radius="0.01"/></geometry></collision>
    <visual><geometry><sphere radius="0.01"/></geometry></visual>
  </link>

  <joint name="base_z" type="prismatic">
    <origin xyz="0 0 0" rpy="0 0 ${PI}"/>
    <parent link="world"/>
    <child link="slider_z"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.5" upper="0.5" effort="500" velocity="1.0"/>
    <dynamics damping="5.0" friction="1.0"/>
  </joint>

  <joint name="base_x" type="prismatic">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="slider_z"/>
    <child link="slider_x"/>
    <axis xyz="1 0 0"/>
    <limit lower="-5.0" upper="5.0" effort="500" velocity="1.0"/>
    <dynamics damping="5.0" friction="0.5"/>
  </joint>

  <joint name="base_to_body" type="fixed">
    <parent link="slider_x"/>
    <child link="base_link"/>
  </joint>

  <!-- ============================================================
       Pelvis / hip_base
       ============================================================ -->
  <link name="hip_base">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass_hip_base}"/>
      <inertia ixx="${I_hip_base_xx}" ixy="${I_hip_base_xy}" ixz="${I_hip_base_xz}"
               iyy="${I_hip_base_yy}" iyz="${I_hip_base_yz}"
               izz="${I_hip_base_zz}"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><box size="${hip_aa_frame_width} ${hip_base_height} ${width}"/></geometry>
      <material name="dark_gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><box size="${hip_aa_frame_width} ${hip_base_height} ${width}"/></geometry>
    </collision>
  </link>

  <!-- FIX: lowered pelvis slightly to ensure feet touch ground -->
  <joint name="pelvis_fixed" type="fixed">
    <origin xyz="-0.09 0 0.844" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="hip_base"/>
  </joint>

  <!-- ============================================================
       Leg macro
       ============================================================ -->
  <xacro:macro name="march6_leg" params="prefix side_sign">

    <link name="${prefix}_hip_aa_side">
      <visual>
        <origin xyz="0 ${side_sign * hip_aa_frame_height/2.0} 0" rpy="0 0 0"/>
        <geometry><box size="${width} ${hip_aa_frame_height} ${width}"/></geometry>
        <material name="dark_gray"/>
      </visual>
      <collision>
        <origin xyz="0 ${side_sign * hip_aa_frame_height/2.0} 0" rpy="0 0 0"/>
        <geometry><box size="${width} ${hip_aa_frame_height} ${width}"/></geometry>
      </collision>
    </link>

    <joint name="${prefix}_hip_aa" type="fixed">
      <origin xyz="0 ${side_sign * hip_base_height/2.0} 0" rpy="0 0 0"/>
      <parent link="hip_base"/>
      <child link="${prefix}_hip_aa_side"/>
    </joint>

    <link name="${prefix}_hip_aa_front">
      <inertial>
        <origin xyz="${-hip_aa_frame_width/2.0} 0 0" rpy="0 0 0"/>
        <mass value="${mass_hip_aa}"/>
        <inertia ixx="${I_hip_aa_xx}" ixy="${I_hip_aa_xy}" ixz="${I_hip_aa_xz}"
                 iyy="${I_hip_aa_yy}" iyz="${I_hip_aa_yz}"
                 izz="${I_hip_aa_zz}"/>
      </inertial>
      <visual>
        <origin xyz="${-hip_aa_frame_width/2.0} 0 0" rpy="0 0 0"/>
        <geometry><box size="${hip_aa_frame_width} ${width} ${width}"/></geometry>
        <material name="dark_gray"/>
      </visual>
      <collision>
        <origin xyz="${-hip_aa_frame_width/2.0} 0 0" rpy="0 0 0"/>
        <geometry><box size="${hip_aa_frame_width} ${width} ${width}"/></geometry>
      </collision>
    </link>

    <joint name="${prefix}_hip_angle_fixed" type="fixed">
      <origin xyz="0 ${side_sign * hip_aa_frame_height} 0" rpy="0 0 0"/>
      <parent link="${prefix}_hip_aa_side"/>
      <child link="${prefix}_hip_aa_front"/>
    </joint>

    <link name="${prefix}_thigh">
      <inertial>
        <origin xyz="0 0 ${-upper_leg_height/2.0}" rpy="0 0 0"/>
        <mass value="${mass_upper_leg}"/>
        <inertia ixx="${I_upper_leg_xx}" ixy="${I_upper_leg_xy}" ixz="${I_upper_leg_xz}"
                 iyy="${I_upper_leg_yy}" iyz="${I_upper_leg_yz}"
                 izz="${I_upper_leg_zz}"/>
      </inertial>
      <visual>
        <origin xyz="0 0 ${-upper_leg_height/2.0}" rpy="0 0 0"/>
        <geometry><box size="${width} ${width} ${upper_leg_height}"/></geometry>
        <material name="dark_gray"/>
      </visual>
      <collision>
        <origin xyz="0 0 ${-upper_leg_height/2.0}" rpy="0 0 0"/>
        <geometry><box size="${width} ${width} ${upper_leg_height}"/></geometry>
      </collision>
    </link>

    <joint name="${prefix}_hip_revolute_joint" type="revolute">
      <origin xyz="${-hip_aa_frame_width} ${side_sign * upper_leg_offset} 0" rpy="0 0 0"/>
      <parent link="${prefix}_hip_aa_front"/>
      <child link="${prefix}_thigh"/>
      <axis xyz="0 1 0"/>
      <limit lower="${hip_min}" upper="${hip_max}" effort="200" velocity="3.0"/>
      <dynamics damping="0.3" friction="0.1"/>
    </joint>

    <link name="${prefix}_shank">
      <inertial>
        <origin xyz="0 0 ${-lower_leg_height/2.0}" rpy="0 0 0"/>
        <mass value="${mass_lower_leg}"/>
        <inertia ixx="${I_lower_leg_xx}" ixy="${I_lower_leg_xy}" ixz="${I_lower_leg_xz}"
                 iyy="${I_lower_leg_yy}" iyz="${I_lower_leg_yz}"
                 izz="${I_lower_leg_zz}"/>
      </inertial>
      <visual>
        <origin xyz="0 0 ${-lower_leg_height/2.0}" rpy="0 0 0"/>
        <geometry><box size="${width} ${width} ${lower_leg_height}"/></geometry>
        <material name="dark_gray"/>
      </visual>
      <collision>
        <origin xyz="0 0 ${-lower_leg_height/2.0}" rpy="0 0 0"/>
        <geometry><box size="${width} ${width} ${lower_leg_height}"/></geometry>
      </collision>
    </link>

    <joint name="${prefix}_knee_revolute_joint" type="revolute">
      <origin xyz="0 ${side_sign * knee_offset} ${-upper_leg_height}" rpy="0 0 0"/>
      <parent link="${prefix}_thigh"/>
      <child link="${prefix}_shank"/>
      <axis xyz="0 -1 0"/>
      <limit lower="${knee_min}" upper="${knee_max}" effort="200" velocity="3.5"/>
      <dynamics damping="0.4" friction="0.4"/>
    </joint>

    <link name="${prefix}_ankle_plate">
      <inertial>
        <origin xyz="0 0 ${-ankle_plate_height/2.0}" rpy="0 0 0"/>
        <mass value="0.01"/>
        <inertia ixx="1e-5" ixy="0" ixz="0"
                 iyy="1e-5" iyz="0"
                 izz="1e-5"/>
      </inertial>
      <visual>
        <origin xyz="0 0 ${-ankle_plate_height/2.0}" rpy="0 0 0"/>
        <geometry><box size="${width} ${width} ${ankle_plate_height}"/></geometry>
        <material name="dark_gray"/>
      </visual>
      <collision>
        <origin xyz="0 0 ${-ankle_plate_height/2.0}" rpy="0 0 0"/>
        <geometry><box size="${width} ${width} ${ankle_plate_height}"/></geometry>
      </collision>
    </link>

    <joint name="${prefix}_ankle_revolute_joint" type="revolute">
      <origin xyz="0 ${side_sign * ankle_plate_offset} ${-lower_leg_height}" rpy="0 0 0"/>
      <parent link="${prefix}_shank"/>
      <child link="${prefix}_ankle_plate"/>
      <axis xyz="0 1 0"/>
      <limit lower="${ankle_min}" upper="${ankle_max}" effort="200" velocity="2.5"/>
      <dynamics damping="0.6" friction="0.3"/>
    </joint>

    <link name="${prefix}_foot">
      <inertial>
        <origin xyz="${(foot_height_backward - foot_height_forward)/2.0} 0 0" rpy="0 0 0"/>
        <mass value="${mass_foot}"/>
        <inertia ixx="${I_foot_xx}" ixy="${I_foot_xy}" ixz="${I_foot_xz}"
                 iyy="${I_foot_yy}" iyz="${I_foot_yz}"
                 izz="${I_foot_zz}"/>
      </inertial>
      <visual>
        <origin xyz="${(foot_height_backward - foot_height_forward)/2.0} 0 0" rpy="0 0 0"/>
        <geometry><box size="${foot_length} ${width} ${width}"/></geometry>
        <material name="red"/>
      </visual>
      <collision>
        <origin xyz="${(foot_height_backward - foot_height_forward)/2.0} 0 0" rpy="0 0 0"/>
        <geometry><box size="${foot_length} ${width} ${width}"/></geometry>
      </collision>
    </link>

    <link name="${prefix}_sole_sensor">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.001"/>
        <inertia ixx="1e-6" ixy="0" ixz="0"
                iyy="1e-6" iyz="0"
                izz="1e-6"/>
      </inertial>

      <visual name="${prefix}_sole_sensor_visual">
        <origin xyz="-0.063 0 0" rpy="0 0 0"/>
        <geometry>
          <!-- FULL SOLE -->
          <box size="${foot_length} ${width} ${sole_thick}"/>
        </geometry>
        <material name="dark_gray"/>
      </visual>
      <collision>
        <origin xyz="-0.063 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${foot_length} ${width} ${sole_thick}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}_foot_to_sole_sensor" type="fixed">
      <origin xyz="0 0 ${-width/2.0 - sole_thick/2.0}" rpy="0 0 0"/>
      <parent link="${prefix}_foot"/>
      <child link="${prefix}_sole_sensor"/>
    </joint>

    <joint name="${prefix}_foot_angle_fixed" type="fixed">
      <origin xyz="0 0 ${-ankle_plate_height}" rpy="0 0 0"/>
      <parent link="${prefix}_ankle_plate"/>
      <child link="${prefix}_foot"/>
    </joint>

  <gazebo reference="${prefix}_sole_sensor">
    <sensor name="${prefix}_sole_contact" type="contact">
      <always_on>1</always_on>
      <update_rate>200</update_rate>
      <contact>
        <collision>${prefix}_ankle_plate_fixed_joint_lump__${prefix}_sole_sensor_collision_2</collision>
      </contact>
    </sensor>
  </gazebo>

  </xacro:macro>

  <xacro:march6_leg prefix="right" side_sign="1"/>
  <xacro:march6_leg prefix="left"  side_sign="-1"/>

  <!-- ros2_control -->
  <ros2_control name="exosuit" type="system">
    <hardware>
      <plugin>gz_ros2_control/GazeboSimSystem</plugin>
    </hardware>

    <joint name="left_hip_revolute_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
    <joint name="left_knee_revolute_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
    <joint name="left_ankle_revolute_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>

    <joint name="right_hip_revolute_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
    <joint name="right_knee_revolute_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
    <joint name="right_ankle_revolute_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
  </ros2_control>

  <gazebo>
    <plugin filename="libign_ros2_control-system.so" name="ign_ros2_control::IgnitionROS2ControlPlugin">
      <robot_param>robot_description</robot_param>
      <robot_param_node>robot_state_publisher</robot_param_node>
      <parameters>$(find exo_control)/config/ros2_controller_march_6.yaml</parameters>
    </plugin>
  </gazebo>

</robot>
